[tool.portray]
name = "AI_Clerk_helper"
version = "0.8.2"
description = ""
authors = ["Allen Lee <allen7575@gmail.com>"]
license = "MIT"
extra_dirs = ["assets"]
extra_markdown_extensions = ["pymdownx.superfences", "pymdownx.highlight"]

[[tool.portray.mkdocs.nav]]
Home = "README.md"

[[tool.portray.mkdocs.nav]]
Changelog = "CHANGELOG.md"

[[tool.portray.mkdocs.nav]]
Troubleshooting = "TROUBLESHOOTING.md"

[[tool.portray.mkdocs.nav]]
    [[tool.portray.mkdocs.nav."Quick Start"]]
    "Installation" = "docs/quick_start/installation.md"

    [[tool.portray.mkdocs.nav."Quick Start"]]
    "CLI" = "docs/quick_start/cli.md"

    [[tool.portray.mkdocs.nav."Quick Start"]]
    "API" = "docs/quick_start/api.md"

    [[tool.portray.mkdocs.nav."Quick Start"]]
    "Configuration" = "docs/quick_start/configuration.md"


[tool.isort]
profile = "black"
multi_line_output = 3

[tool.interrogate]
ignore-init-method = true
ignore-init-module = false
ignore-magic = false
ignore-semiprivate = false
ignore-private = false
ignore-property-decorators = false
ignore-module = false
ignore-nested-functions = false
ignore-nested-classes = true
ignore-setters = false
fail-under = 95
exclude = ["setup.py", "docs", "build"]
ignore-regex = ["^get$", "^mock_.*", ".*BaseClass.*"]
verbose = 2
quiet = false
whitelist-regex = []
color = true
generate-badge = "assets"
badge-format = "svg"